runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: a814j91hsofa83hi01
  MASTER_KEY: 18hosf0u3joadosdfio20ajohf02h34
  PARSE_MOUNT: /parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:
